#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# Ответы кэшируются вне репо, чтобы секрет не попал в git и перезапуск
# подхватывал уже введённые значения.
ENV_FILE="$HOME/.wheee-discord-wizard.env"

VPS="root@64.176.74.237"
VPS_IP="64.176.74.237"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

banner "wheee → Discord Activity: запуск"

# ── Stage 1: DNS ───────────────────────────────────────────────────────────
stage "DNS: discord.wheee.io"
say "Новый поддомен живёт на том же Польском VPS, что и api.wheee.io."
step "В панели DNS-провайдера домена wheee.io добавьте A-запись:"
say ""
say "    discord.wheee.io  →  $VPS_IP"
say ""
note "TTL любой; проксирующие режимы (оранжевое облако Cloudflare и т.п.) не включать —"
note "Discord-прокси должен ходить прямо на VPS."
pause "Запись добавлена? Enter — проверяю."
while true; do
  got="$(dig +short discord.wheee.io | tail -n1)"
  if [[ "$got" == "$VPS_IP" ]]; then
    say "${GREEN}✓ dig вернул $got — DNS на месте.${RESET}"
    break
  fi
  warn "dig вернул '${got:-ничего}' (жду $VPS_IP) — запись ещё не разъехалась."
  if ! confirm "Подождать и проверить ещё раз?"; then
    SKIPPED+=("DNS ещё не разъехался — проверить позже: dig +short discord.wheee.io")
    break
  fi
  sleep 15
done

# ── Stage 2: Developer Portal ──────────────────────────────────────────────
stage "Discord Developer Portal: прод-приложение"
open_url "https://discord.com/developers/applications"
step "New Application → имя «wheee» (это ПРОД-приложение; dev-приложения — отдельно, стадия 8)."
step "Installation → включить оба контекста: User Install И Guild Install."
step "OAuth2 → Redirects → добавить: https://127.0.0.1"
step "Activities → Settings → включить Enable Activities."
step "Activities → Settings → Supported Platforms: оставить только Web (iOS/Android выключить — v1)."
say ""
step "Activities → URL Mappings — СТРОГО в этом порядке (специфичный префикс выше корня):"
say "    1) PREFIX /gameapi   TARGET api.wheee.io"
say "    2) PREFIX /          TARGET discord.wheee.io"
say ""
pause "Готово? Enter — теперь ключи."
step "General Information → App ID (он же Client ID) — скопируйте."
ask DISCORD_CLIENT_ID "Client ID:"
step "OAuth2 → Client Secret → Reset Secret (если ещё не выпускали) → скопируйте."
ask_secret DISCORD_CLIENT_SECRET "Client Secret (ввод скрыт):"
write_env DISCORD_CLIENT_ID "$DISCORD_CLIENT_ID"
write_env DISCORD_CLIENT_SECRET "$DISCORD_CLIENT_SECRET"
say ""
if confirm "Портал навязал маппингам префикс /.proxy (или иной), которого вы не вводили?"; then
  ask DISCORD_PROXY_PREFIX "Какой префикс подставился? (например /.proxy):"
  write_env DISCORD_PROXY_PREFIX "$DISCORD_PROXY_PREFIX"
  SKIPPED+=("Поменять API_BASE в packages/client/src/lib/config.ts: '/gameapi' → '${DISCORD_PROXY_PREFIX}/gameapi' (скажите Claude — это одна строка + редеплой)")
  warn "Записал. До правки config.ts игра внутри Discord до сервера не достучится."
fi

# ── Stage 3: push + заливка env на VPS + деплой ────────────────────────────
stage "Деплой: push, env на VPS, пересборка"
say "Деплой делает git pull на VPS — сперва пушим main."
if [[ -n "$(git -C "$REPO_ROOT" status --porcelain)" ]]; then
  warn "В репо незакоммиченные изменения — deploy-all сам спросит, но лучше глянуть."
fi
ahead="$(git -C "$REPO_ROOT" rev-list '@{upstream}..HEAD' --count 2>/dev/null || echo '?')"
if [[ "$ahead" != "0" ]]; then
  say "Локальный main впереди origin на $ahead коммит(ов)."
  if confirm "Запушить сейчас (git push)?"; then
    git -C "$REPO_ROOT" push
    say "${GREEN}✓ запушено.${RESET}"
  else
    SKIPPED+=("git push не сделан — деплой подтянет старый код")
  fi
else
  say "${GREEN}✓ origin уже в курсе.${RESET}"
fi
say ""
say "Заливаю три ключа в /opt/wheee/deploy/.env на VPS (upsert, ничего не трёт):"
say "    DISCORD_CLIENT_ID, DISCORD_CLIENT_SECRET, VITE_DISCORD_CLIENT_ID (= Client ID)"
if confirm "Залить на $VPS?"; then
  ssh "$VPS" bash -s -- "$DISCORD_CLIENT_ID" "$DISCORD_CLIENT_SECRET" <<'REMOTE'
set -euo pipefail
f=/opt/wheee/deploy/.env
cid="$1"; secret="$2"
upsert() { sed -i "/^$1=/d" "$f"; printf '%s=%s\n' "$1" "$2" >> "$f"; }
upsert DISCORD_CLIENT_ID "$cid"
upsert DISCORD_CLIENT_SECRET "$secret"
upsert VITE_DISCORD_CLIENT_ID "$cid"
echo "ok: $(grep -c '^\(VITE_\)\?DISCORD_' "$f") discord-строк в $f"
REMOTE
  say "${GREEN}✓ env на VPS обновлён.${RESET}"
else
  SKIPPED+=("env на VPS не залит — добавить три DISCORD-переменные в /opt/wheee/deploy/.env руками")
fi
say ""
step "Теперь В ДРУГОМ ТЕРМИНАЛЕ (скрипт интерактивный, спросит подтверждения):"
say "    cd $REPO_ROOT && bash deploy/deploy-all.sh --server"
note "Это sync-env + git pull + docker compose up -d --build: соберёт discord-бандл"
note "(VITE_DISCORD_CLIENT_ID уходит build-arg'ом) и поднимет nginx с хостом discord.wheee.io."
pause "Деплой отработал? Enter — проверяю, что хост отвечает."
code="$(curl -sk -o /dev/null -w '%{http_code}' "https://discord.wheee.io/" || echo 000)"
if [[ "$code" == "200" ]]; then
  say "${GREEN}✓ https://discord.wheee.io отвечает 200 (сертификат пока старый — норм, следующая стадия).${RESET}"
else
  warn "https://discord.wheee.io ответил '$code' (жду 200). Проверьте деплой: docker compose ps на VPS."
  SKIPPED+=("discord.wheee.io не отдал 200 — разобраться с деплоем до стадии сертификата")
fi

# ── Stage 4: сертификат ────────────────────────────────────────────────────
stage "Сертификат: расширить на discord.wheee.io"
say "Все три домена делят один cert /etc/letsencrypt/live/ru.wheee.io/ — его надо"
say "расширить (--expand), не выпускать отдельный."
say ""
step "Зайдите на VPS:  ssh $VPS"
step "Сначала разведка — КАК выпущен текущий cert (webroot / standalone / хостовый certbot):"
say "    cd /opt/wheee/deploy && docker compose config | grep -A3 certbot"
say "    crontab -l | grep -i certbot ; history | grep -i certbot | tail"
say ""
step "Если webroot (стандарт для этого compose) — команда:"
say "    docker compose run --rm certbot certonly --webroot -w /var/www/certbot --expand \\"
say "      -d ru.wheee.io -d api.wheee.io -d discord.wheee.io"
step "Если standalone/хостовый certbot — тем же способом, что выпускался текущий, добавив -d discord.wheee.io."
step "После успеха:  docker compose restart nginx"
warn "Если certbot ругнётся на webroot-путь — механизм другой; не подбирать наугад, спросить Claude с выводом разведки."
pause "Cert расширен и nginx перезапущен? Enter — проверяю SAN."
san="$(echo | openssl s_client -connect discord.wheee.io:443 -servername discord.wheee.io 2>/dev/null | openssl x509 -noout -ext subjectAltName 2>/dev/null || true)"
if echo "$san" | grep -q "discord.wheee.io"; then
  say "${GREEN}✓ сертификат покрывает discord.wheee.io.${RESET}"
else
  warn "discord.wheee.io в SAN не найден. Сейчас в сертификате: ${san:-не удалось прочитать}"
  SKIPPED+=("Сертификат ещё не покрывает discord.wheee.io — перепроверить certbot")
fi

# ── Stage 5: smoke в Discord ───────────────────────────────────────────────
stage "Smoke: Activity запускается, логин проходит"
step "Discord (desktop или https://discord.com в браузере) → Settings → Advanced → включить Developer Mode."
step "Зайдите в голосовой канал на любом сервере, где меньше 25 участников (лимит неверифицированных Activities)."
step "Rocket-кнопка (🚀 у панели войса) → Developer Activity Shelf → выберите wheee."
say ""
say "Что должно произойти: игра грузится, в лобби видно ваше Discord-имя (логин прошёл)."
warn "Если игра грузится, но вы «аноним» — auth упал. Диагностика на VPS:"
say "    docker compose logs app --since 10m | grep -i discord"
note "403 'Forbidden origin' будет значить, что прокси Discord доносит неожиданный Origin —"
note "скопируйте лог и скажите Claude, это правится одной регуляркой в oauth.ts."
if confirm "Activity загрузилась и логин прошёл?"; then
  say "${GREEN}✓ smoke пройден.${RESET}"
else
  SKIPPED+=("Smoke в Discord не пройден — вернуться после диагностики")
fi

# ── Stage 6: RTT-гейт ──────────────────────────────────────────────────────
stage "RTT-гейт: прокси Discord vs напрямую"
say "Гейт перед дальнейшей полировкой: медиана RTT через прокси из ЕС должна быть < 150 мс."
say ""
step "Проще всего мерить в БРАУЗЕРНОМ Discord (discord.com): запустите Activity, F12 → Console."
step "Вставьте сниппет (меряет 40 пинг-понгов по игровому протоколу):"
say ""
say '    (async () => {'
say "      const url = location.origin.replace('https','wss') + '/gameapi/ws';"
say '      const ws = new WebSocket(url); await new Promise(r => ws.onopen = r);'
say '      const rtts = [];'
say '      for (let i = 0; i < 40; i++) {'
say '        const t = performance.now();'
say '        ws.send(JSON.stringify({type:"ping"}));'
say '        await new Promise(r => ws.onmessage = e => { if (JSON.parse(e.data).type === "pong") r(); });'
say '        rtts.push(performance.now() - t);'
say '      }'
say '      rtts.sort((a,b) => a-b); ws.close();'
say '      console.log("median RTT:", rtts[20].toFixed(1), "ms");'
say '    })()'
say ""
step "Для сравнения: тот же сниппет в обычной вкладке на https://wheee.io, заменив url на 'wss://api.wheee.io/ws'."
ask RTT_PROXY_MS "Медиана через прокси, мс:"
ask RTT_DIRECT_MS "Медиана напрямую, мс:"
write_env RTT_PROXY_MS "$RTT_PROXY_MS"
write_env RTT_DIRECT_MS "$RTT_DIRECT_MS"
if [[ "${RTT_PROXY_MS%%.*}" =~ ^[0-9]+$ ]] && (( ${RTT_PROXY_MS%%.*} < 150 )); then
  say "${GREEN}✓ гейт пройден (${RTT_PROXY_MS} мс < 150 мс) — полировка Discord-версии оправдана.${RESET}"
else
  warn "Гейт НЕ пройден (${RTT_PROXY_MS} мс). Полировку геймплея отложить, сначала латентность."
  SKIPPED+=("RTT через прокси ${RTT_PROXY_MS} мс ≥ 150 — обсудить с Claude (регион VPS/оверхед Cloudflare Workers)")
fi

# ── Stage 7: прод-проверка вдвоём ──────────────────────────────────────────
stage "Прод-проверка: автоматч, инвайт, аналитика"
step "Двое (вы + кто-то) заходят в ОДИН голосовой канал (сервер <25 участников) → оба открывают Activity."
say "    Ожидание: автоматч 1v1 без ручного создания комнаты (пары матчатся автоматически)."
step "Один создаёт инвайт кнопкой в игре → shareLink → второй человек (можно из ЛС) открывает ссылку."
say "    Ожидание: у получателя Activity стартует и матчит его по коду."
step "Аналитика (нужен STATS_TOKEN из /opt/wheee/deploy/.env):"
say "    curl -s 'https://api.wheee.io/api/events/summary?token=ВАШ_ТОКЕН' | grep -o 'discord'"
say "    Ожидание: platform 'discord' появился в платформенной сводке."
if confirm "Все три проверки прошли?"; then
  say "${GREEN}✓ Discord-канал боевой.${RESET}"
else
  SKIPPED+=("Прод-проверка не закрыта — повторить после фиксов")
fi

# ── Stage 8: dev-петля (опционально) ───────────────────────────────────────
stage "Dev-петля для локальной разработки (опционально)"
if confirm "Настроить локальную dev-петлю сейчас?"; then
  step "Создайте в Developer Portal ОТДЕЛЬНОЕ dev-приложение (повторив стадию 2, ключи не заливать на VPS!)."
  step "Два туннеля в двух терминалах:"
  say "    cloudflared tunnel --url http://localhost:5173    # клиент"
  say "    cloudflared tunnel --url http://localhost:3001    # сервер"
  step "В DEV-приложении URL Mappings: '/' → туннель клиента, '/gameapi' → туннель сервера."
  step "Локально поднять:"
  say "    bun run dev:server"
  say "    VITE_PLATFORM=discord VITE_DISCORD_CLIENT_ID=<dev app id> bun run dev:client"
  step "Discord → войс → Rocket → своё dev-Activity."
  warn "После тестов сбросить URL Mappings dev-приложения с чужих туннель-доменов (защита от перехвата)."
  pause "Понятно? Enter."
else
  note "Пропущено — инструкция живёт в marketing/DISCORD_LAUNCH_CHECKLIST.md §5."
fi

# ── Stage 9: параллельный трек ─────────────────────────────────────────────
stage "Параллельный трек: верификация и дистрибуция (инфо)"
say "Не блокирует запуск, но без этого Activity видна только серверам <25 участников:"
step "Team-аккаунт в Developer Portal (перевесить приложение с личного аккаунта на команду)."
step "Identity + App Verification (Developer Portal → App Verification) — календарно недели."
step "Метаданные и арты для App Directory — см. marketing/DISCORD_ACTIVITIES_INTEGRATION_RESEARCH.md §7."
step "После верификации: Discovery opt-in → появление в каталоге до 24 часов."
note "Монетизация Premium Apps — только юрлица US/EU/UK; для этого канала план — дистрибуция, не выручка."
pause "Финиш. Enter."
# ──────────────────────────────────────────────────────────────────────────

finish
